# Run parallel jobs to sum each of the several partial files.

log    =    log/$(Cluster)_$(file).log
error  =  error/$(Cluster)_$(file).err
output = output/$(Cluster)_$(file).out

universe = vanilla

executable = ./cleanup.sh
arguments = $(file)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $(file)

request_cpus = 1
request_memory = 1GB
request_disk = 3MB

queue file from inputFileList